title: Privilege
email: incoder.xu@gmail.com
description: >- 
  高性能、组件化、开源源码权限管理系统.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
    zip_url: https://github.com/TwoDragonLake/privilege/master
    tar_url: https://github.com/TwoDragonLake/privilege/master
